### PR TITLE
Async syntax in deploy script

### PR DESCRIPTION
**Pull request by maryokhin**
Test deployment run after changes:
```
Running migration: 2_deploy_contracts.js
  Deploying RocketStorage...
  ... 0x4993cb4d04bc57168a0c4e05e968554bddd5885250b2692fc6b6d9973afb6643
  RocketStorage: 0x56ff12c2bdeaddedab972109f3c9421279dccf29
Saving successful migration to network...
  Deploying DummyCasper...
  ... 0xeeab0e8532564fd7b4c80236d7ad491230017841e7008d7a0eeeac398d5f3f2a
Saving artifacts...
  ... 0x4fe51cea533b158d9553acc0d920abe9fc83eefc0dcfe291acdabb5c5c8fb027
  DummyCasper: 0xd1757d951a82e613d617ee9f77c8f1fb3927c279
  ... 0x3845fe908570345e1e4a67ec58cb64cfc72ca9919804ab66a3d56cf896cb7add
  Deploying RocketVault...
  ... 0x603044c1c69c8085aa3c63288c9140e6db277656e6a23babe0e2d0e876db2ddd
  RocketVault: 0x8e24f84e70d6f0d7e25e79f1c94326bb234ce44f
  Deploying RocketUtils...
  ... 0xe459fba50dee9cd0c4f836220221708eb8fff2c96a6992f3149136c0b2c6fbe2
  RocketUtils: 0xb0d8eac3363ed084dadd1e8dd5ea74054c07b584
  Deploying RocketUpgrade...
  ... 0xf91c404c6cb1176c7462a1ca93ba5515167aa0a171ba00662722c63aca6f5a2b
  RocketUpgrade: 0x3008085096224432b1fce1664fee89bf0b955077
  Deploying RocketRole...
  ... 0x43c5559eb5f41fa0012f3bd050d748fff0f305923186696e2799fbcd419180c8
  RocketRole: 0x1e222dc4b59988b75b6dd2056a0715afbd9b5f61
  Deploying RocketUser...
  ... 0x82200c3df7d9172d79c3760678113dc26cc8b2dae57a6f71e5c56ae54d5281e8
  RocketUser: 0xe79fe068b8cce2b3dea2d747bc9301dfa0948043
  Deploying RocketPartnerAPI...
  ... 0x181bd5d203ceb49c8dbca55d1b5a12f9874bcd0294a3028c312ca36ca74d2c6c
  RocketPartnerAPI: 0x2c50852b61fd0fe2dd488bc7ccba441d445c4753
  Deploying RocketDepositToken...
  ... 0xece4d00309223a67d475ca09c4f1ca939413db4e4047ab11ce4c4924fad913b2
  RocketDepositToken: 0xefc5a0a4bebf5a09e2b4d1714c12bf33185bc04f
  Deploying RocketFactory...
  ... 0xdec6bc20ffe193327b992382dbc1d30ceb2e5d50d37832b1e0c6bdd7a33e14fa
  RocketFactory: 0xe3f1b77f6ca91ee867d6bc7bad9565a21aa9e1d6
  Deploying RocketSettings...
  ... 0x59096c5e8ef0d495dacb5aa30e19f9f26cf730d11f767c28b9999dd28cba2917
  RocketSettings: 0xc58ed88d8fee01862627389796f6b23fa5b321b0
  Deploying RocketPool...
  ... 0x1ecbe2b51a23473383bb335d4daf2c0a0f24e0e01b0f618c08d6236137f45458
  RocketPool: 0x77c13783d0d827975093c3678b66c313cb4f2930
  Deploying RocketNode...
  ... 0x07ac3dd30745731a0cb0a7c6633000dc6d50f780a30a5699bb72a1c1e4067cd0
  RocketNode: 0xafe758c7c5c3315e906b10a482a2202d99462b60
  Deploying RocketPoolMiniDelegate...
  ... 0x70db49792881ec93e81a77460f3321c561ec149b53d03ab5fa3445b7a03f1902
  RocketPoolMiniDelegate: 0x9ad86aa0c2528eb7b1819893fb3d16763e1d4f15


Set Storage Address:
0x56ff12c2bdeaddedab972109f3c9421279dccf29
  ... 0x406f4763b942768c122ae4258eccfd3eb3aa8d89bce9a9410e0a30f6db4bbe7b
  ... 0x5977c0843d253fcaf9b6758a0c439674147de9de415fef2acb272457e0dd63f7
Set Storage DummyCasper Address:
0xd1757d951a82e613d617ee9f77c8f1fb3927c279
  ... 0x953f1271828dc3eeb6adeb5836a5f65dd3dcbdc71af96852840a583cc94dca8e
  ... 0xf0617f375e722eb051c6270960bfde137c1a71167348d26eb9c8b8e2c19b5ba4
Set Storage RocketPool Address:
0x77c13783d0d827975093c3678b66c313cb4f2930
  ... 0x1cf06e8606f08b76106bd59653c3e98d5492dd2393baa08eb8188d624d8cd9c1
  ... 0xd76a6f1975dbca0a5470df3c5dbace722e82e59ded85e07c39e6a483cb57251f
Set Storage RocketRole Address:
0x1e222dc4b59988b75b6dd2056a0715afbd9b5f61
  ... 0xf154c62c930737c59c892f3a129a3fed4d7239125a8e0d6b3a019c7c546eb4fa
  ... 0xddcc6605e85076902b369cc09fc867eee47019d727279e68865babcd1c2bb1fe
Set Storage RocketUser Address:
0xe79fe068b8cce2b3dea2d747bc9301dfa0948043
  ... 0xfff5122bc2017371526ff5b1de03491245a76cda23388f8e4fc6532654e9e298
  ... 0x7a798fbc8db154abe62207e1aff1b639a5d99406567e3aea8420110e5f62220a
Set Storage RocketNode Address:
0xafe758c7c5c3315e906b10a482a2202d99462b60
  ... 0x3fe386c9174dad324e8db4c75f8b2bf39532f65b1717ea4f65d69ed620389d9b
  ... 0xdf4005458d10d8e46bd4f8838932277a4ae0d6127e4ffef2c240365095a1ee5f
Set Storage RocketPoolMiniDelegate Address:
0x9ad86aa0c2528eb7b1819893fb3d16763e1d4f15
  ... 0xf7dc807b17c783fdf104066d3c655d08f0cb66ea4cf94b6cacf7a899551ccfc1
  ... 0xa90b4679b42cb4ce4251b6a698aa33c9f3560accdc847e7d048429d85f5b583c
Set Storage RocketFactory Address:
0xe3f1b77f6ca91ee867d6bc7bad9565a21aa9e1d6
  ... 0xbdb983115e261b94b50466d30677348e9daaa133641d095b08ab0b51a28dcd33
  ... 0x096ecfda5cf969e514675208702f2eb6021f34f44b5d7d5e47d5dca7cfcd6b89
Set Storage RocketUpgrade Address:
0x3008085096224432b1fce1664fee89bf0b955077
  ... 0x2452700be5f29685d1e10f97ccd10229149190e63056ce7c365cc292ba5ac54a
  ... 0xc2b827d0cbed678eb91ca26c9c01ec2143e1f2e33316e1418932b1aa7cefc957
Set Storage RocketUtils Address:
0xb0d8eac3363ed084dadd1e8dd5ea74054c07b584
  ... 0xbd3fd37c105175e69b1f84a853901e63dfcc2fc5866cb06a28dc3024cd4e7e98
  ... 0xc2d7d262e84071ee65c1b238f4b8035d3518dcd8f0152d21948fd71f5a05adc5
Set Storage RocketPartnerAPI Address:
0x2c50852b61fd0fe2dd488bc7ccba441d445c4753
  ... 0x559d9368f140a9c81643cfd6f808cc19812196d34114eba72699cb6b346544b4
  ... 0x9bada5fd2d3a4b3cfd8e55fd0d5deb36a1ca5aaaf172d5abc6801c2dbb7c699a
Set Storage RocketDepositToken Address:
0xefc5a0a4bebf5a09e2b4d1714c12bf33185bc04f
  ... 0xe0cd6e0a918d3ac8a74e8f82a5910e7b03b3cd8f5e7cbfd099f49c1e10e080eb
  ... 0xa3c44c75137bfc7a68a3e3e3ffcf5fe43e330518cef41d3116fdfb138b7e7e1d
Set Storage RocketVault Address:
0x8e24f84e70d6f0d7e25e79f1c94326bb234ce44f


  ... 0xcf467a29ff1c70fde3c8d7d8ef1294caad11eb11276db8874348bbb2368ff1ec
  ... 0x80a3561fc2892d454c11f18c4d5aca9ea7897160c1ae3046131de5553f9f2ce9
Set Storage RocketSettings Address:
0xc58ed88d8fee01862627389796f6b23fa5b321b0


  ... 0x6545ccc443d2609a4d74db5d03cf2d8f71dd2c7ecc0e3091755dbc6fc3ea135f
Post - Settings Initialised
  ... 0x69adefc44f1105bf9875d9db24973ccf58284e033f579f482978296f3c9b5be2
Post - Storage Direct Access Removed
  Running step...
```

### CODE REVIEW

**Comment by darcius** [comment]
Nice one Tymur, that callback cascade has been an eye sore for a while, good to see Truffle deploy supports it now.

One issue though, 'npm test' fails now and 'truffle deploy' works, Darren also gets the same issue.. I'm running:

Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)

**Comment by maryokhin** [comment]
Resolved the merge conflict, looking in to the test failure.

**Comment by maryokhin** [comment]
It seems that async works in isolation, but for some reason is failing during tests.
```
  Contract: RocketPool
    1) "before each" hook for "owner: fail to access storage directly after deployment"


  0 passing (272ms)
  1 failing

  1) Contract: RocketPool "before each" hook for "owner: fail to access storage directly after deployment":
     Error: RocketSettings has not been deployed to detected network (network/artifact mismatch)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:454:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)
```
Either that, or it's not working in general and failing in tests because they are triggering the actual contract functions.

**Comment by darcius** [comment]
Yeah it's an odd one. I'll give it some more testing but will leave this PR open until we can resolve it.

**Comment by darcius** [comment]
Resolved in https://github.com/rocket-pool/rocketpool/pull/35

**Pull request closed without merging**
